{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bjj-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bjj-frontend.labels" . | nindent 4 }}
spec:
  {{- if .Values.frontend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  {{- else if .Values.frontend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.frontend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bjj-frontend.selectorLabels" . | nindent 6 }}
{{- end }}
