{{- if and .Values.frontend.enabled .Values.frontend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bjj-frontend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bjj-frontend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.frontend.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.azure.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId | quote }}
    {{- end }}
automountServiceAccountToken: {{ .Values.frontend.serviceAccount.automount | default false }}
{{- end }}