{{- if and .Values.api.enabled .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bjj-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bjj-api.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.api.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.azure.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.clientId | quote }}
    {{- end }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automount | default true }}
{{- end }}
