apiVersion: v2
name: bjj-api
description: A Helm chart for the BJJ Éire API — Java 25 / Spring Boot Web API
type: application
version: 0.1.7
appVersion: "1.0.0"
keywords:
  - api
  - java
  - spring-boot
  - bjj
maintainers:
  - name: DevOps Team
    email: devops@example.com
