bjj-mongodb:
  mongodb:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    persistence:
      storageClassName: standard
      size: 2Gi
    metrics:
      enabled: true

bjj-api:
  api:
    image:
      repository: bjj-api
      tag: "local"
      pullPolicy: Never
    springProfiles: ""
    env:
      BJJEIRE_CORS_ALLOWEDORIGINS_0: "https://localhost:5173"
      BJJEIRE_CORS_ALLOWEDORIGINS_1: "http://localhost:5173"
      BJJEIRE_CORS_ALLOWEDORIGINS_2: "https://app.bjj.local"
      BJJEIRE_CORS_ALLOWEDORIGINS_3: "http://app.bjj.local"
      RATE_LIMIT_ENABLED: "false"
      RATE_LIMIT_PERMIT_LIMIT: "5"
      RATE_LIMIT_WINDOW_SECONDS: "10"
      RATE_LIMIT_REJECTION_STATUS_CODE: "429"
      READ_ONLY_MODE_ENABLED: "true"
      FEATURE_BJJ_EVENTS: "true"
      FEATURE_GYMS: "true"
      FEATURE_STORES: "true"
      FEATURE_COMPETITIONS: "true"
      DONATION_BITCOIN_ADDRESS: ""

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

  ingress:
    hosts:
      - host: api.bjj.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: bjj-tls-secret
        hosts:
          - api.bjj.local

bjj-frontend:
  frontend:
    image:
      repository: bjj-frontend
      tag: "local"
      pullPolicy: Never
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 101
      fsGroup: 101
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 101
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
    env:
      NODE_ENV: production
      PORT: "80"
      SERVICES_API_HTTP_0: "http://bjj-api:8080"
    autoscaling:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    waitForApi:
      enabled: false

  ingress:
    hosts:
      - host: app.bjj.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: bjj-tls-secret
        hosts:
          - app.bjj.local

seeder:
  enabled: true
  dataset: "test"
  image:
    repository: bjj-seeder
    tag: "local"
    pullPolicy: Never
