bjj-mongodb:
  mongodb:
    persistence:
      storageClassName: standard
      size: 5Gi
bjj-api:
  api:
    image:
      repository: ghcr.io/ianoflynnautomation/bjjeire-api
      pullPolicy: IfNotPresent
      tag: ""
    env:
      BJJEIRE_CORS_ALLOWEDORIGINS_0: "https://dev.bjjeire.ie"
      BJJEIRE_CORS_ALLOWEDORIGINS_1: "http://dev.bjjeire.ie"
      RATE_LIMIT_ENABLED: "false"
      RATE_LIMIT_PERMIT_LIMIT: "5"
      RATE_LIMIT_WINDOW_SECONDS: "10"
      RATE_LIMIT_REJECTION_STATUS_CODE: "429"
      READ_ONLY_MODE_ENABLED: "true"
      FEATURE_BJJ_EVENTS: "true"
      FEATURE_GYMS: "true"
      FEATURE_STORES: "true"
      FEATURE_COMPETITIONS: "true"
      DONATION_BITCOIN_ADDRESS: ""
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: api.dev.bjjeire.ie
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: bjj-dev-tls-secret
        hosts:
          - api.dev.bjjeire.ie
bjj-frontend:
  frontend:
    image:
      repository: ghcr.io/ianoflynnautomation/bjjeire-frontend
      pullPolicy: IfNotPresent
      tag: ""
    env:
      NODE_ENV: production
      PORT: "80"
      SERVICES_API_HTTP_0: "http://bjj-api:8080"
    autoscaling:
      enabled: false
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: dev.bjjeire.ie
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: bjj-dev-tls-secret
        hosts:
          - dev.bjjeire.ie
seeder:
  dataset: "test"
  image:
    repository: ghcr.io/ianoflynnautomation/bjjeire-seeder
    pullPolicy: Always
    tag: "0.1.6"
