bjj-mongodb:
  mongodb:
    persistence:
      storageClassName: standard
      size: 5Gi
bjj-api:
  api:
    image:
      repository: ghcr.io/ianoflynnautomation/bjjeire-api
      pullPolicy: IfNotPresent
      tag: ""
    env:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_HTTP_PORT: "80"
      CorsOptions__AllowedOrigins: "https://dev.bjjeire.ie,http://dev.bjjeire.ie"
      CorsOptions__AllowedMethods: "GET,POST,PUT,DELETE"
      CorsOptions__AllowedHeaders: "Authorization,Content-Type"
      RateLimitOptions__EnableRateLimiting: "false"
      RateLimitOptions__PermitLimit: "5"
      RateLimitOptions__WindowInSeconds: "10"
      RateLimitOptions__RejectionStatusCode: "429"
      CacheOptions__DefaultExpirationMinutes: "5"
      ReadOnlyMode__Enabled: "true"
      CompetitionDeactivation__Interval: "1.00:00:00"
      CompetitionDeactivation__InitialDelay: "00:00:30"
      FeatureManagement__BjjEvents: "true"
      FeatureManagement__Gyms: "true"
      FeatureManagement__Stores: "true"
      FeatureManagement__Competitions: "true"
      ServiceDefaults__ServiceName: "BjjEire.Api"
      ServiceDefaults__EnablePrometheus: "false"
      AzureAd__Instance: "https://login.microsoftonline.com/"
      AzureAd__TenantId: ""
      AzureAd__ClientId: ""
      AzureAd__Audience: ""
      Donation__BitcoinAddress: ""
      Serilog__Properties__Application: "BjjWorld.Api"
      OTEL_EXPORTER_OTLP_ENDPOINT: ""
      OTEL_RESOURCE_ATTRIBUTES__service.name: "BjjWorld.Api"
      OTEL_RESOURCE_ATTRIBUTES__deployment.environment: "Staging"
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: api.dev.bjjeire.ie
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: bjj-dev-tls-secret
        hosts:
          - api.dev.bjjeire.ie
bjj-frontend:
  frontend:
    image:
      repository: ghcr.io/ianoflynnautomation/bjjeire-frontend
      pullPolicy: IfNotPresent
      tag: ""
    env:
      NODE_ENV: production
      PORT: "80"
      SERVICES_API_HTTP_0: "http://bjj-api:80"
    autoscaling:
      enabled: false
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: dev.bjjeire.ie
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: bjj-dev-tls-secret
        hosts:
          - dev.bjjeire.ie
seeder:
  dataset: "test"
  image:
    repository: ghcr.io/ianoflynnautomation/bjjeire-seeder
    pullPolicy: Always
    tag: "0.1.6"
